<?php
/**

 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
?>
<div id="clearandfizzy_reducedcheckout_login" class="">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        
		<div class="">

			<ul class="form-list">
				<li class="fields">
					<h2><?php echo $this->__('My Email Address');?></h2>
					<div class="">
						<div class="input-box">
							<input type="text" name="login[username]" class="input-text required-entry validate-email" id="login-email" title="Email" value="" />
						</div>
					</div>
				</li>
				<li class="fields">&nbsp;</li>
				<li class="fields">
					<h2 class=""><?php echo $this->__('Are you already a customer?') ?></h2>
				</li>
				<li class="fields">
   					<ul class="form-list">
                		<li class="control">
                		<input type="radio" name="checkout_method" id="login:guest" value="guest" class="radio" /><label for="login:guest"><?php echo $this->__("No, I'm a new customer") ?></label>
		                </li>
		                <li class="control">
		                	<div>
        		            <input type="radio" name="checkout_method" id="login:login" value="login" class="radio" checked="checked" /><label for="login:login"><?php echo $this->__('Yes, and my password is') ?></label>
							<div class="">
								<div class="input-box">
									<input type="password" name="login[password]" class="input-text required-entry validate-password" id="login-password" title="Password" value="" />
								    <input name="context" type="hidden" value="checkout" />
								</div>
							</div>	
       		            </li>
		            </ul>
				</li>
				
				<li class="fields">
					<div class="">
			            <button id="submit" type="submit" title="Continue" class="button"><span><span>Continue</span></span></button>
			        </div>			
				</li>
			</ul>
		</div>        
		</form>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);

    $('login-password').observe('keypress', bindLoginPost);
    $('submit').observe('click', submitCheckout);
    
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function submitLoginCheckout()
    {
    	if(loginForm.validator && loginForm.validator.validate()){
        	//$('submit').disabled = true;

        	$('login-form').submit();
        }
    }

	$('login\:guest').observe('click', bindRadioClick);
	$('login\:login').observe('click', bindRadioClick);

	function bindRadioClick(e) {
		
 		switch (this.identify()) {

	 		case "login:guest":
	 			$('login-password').value = '';
	 			$('login-password').addClassName('disabled');
	 			$('login-password').removeClassName('required-entry');
	 			$('login-password').removeClassName('validate-password');
	 			$('login-password').disable();
		 	break;

	 		case "login:login":
	 			$('login-password').removeClassName('disabled');
	 			$('login-password').addClassName('required-entry');
	 			$('login-password').addClassName('validate-password');	 			
	 			$('login-password').enable();		 		
	 		break;

 		} // end switch

	} // end function 

	function submitCheckout(e) {
		
		if ( $('login\:guest').checked == true ) {
			submitGuestCheckout(e);
		} else {
			submitLoginCheckout();
		}
	} // end 
	
	function submitGuestCheckout(e) {
		$('billing:email').value = $('login-email').value;
		checkout.setMethod();
		Event.stop(e);
	} // end fun

	
//]]>
</script>
